### PR TITLE
AMP-218

### PR DESCRIPTION
**Pull request by yingfeng-iu**
- updated .gitignore to include config files into version control
- added galaxy.yml with admin_users

### CODE REVIEW

**Comment by martenson** [comment]
@yingfeng-iu This is generally not something you want to do, since some of the values here are secret (like db password or id_secret)

**Comment by yingfeng-iu** [comment]
@martenson thank you for the reminder. I'm new to Galaxy and didn't notice there're pw entries in galaxy.yml. My thought to include it in the repo is that there are many properties in galaxy.yml that we might want to share among developers and different environments. Is there an easy way to hook a separate properties file where we can put all credentials instead of in galaxy.yml?

**Comment by martenson** [comment]
@yingfeng-iu It is reasonable to have config files version controlled, but I suggest using a private repository for that. 

at usegalaxy.org we use [repositories](https://github.com/galaxyproject/usegalaxy-playbook/blob/master/env/main/group_vars/galaxyservers/vars.yml) with ansible playbooks to backup configurations (with secret values encrypted) but that might be a bit too heavy weight for a simple instance. Maybe worth, I don't know your scope.

**Comment by yingfeng-iu** [comment]
@martenson thanks for the info! I'll discuss with our team on how to resolve this.

**Pull request merged**
